### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by RickyWang111** [techleadhd/chatgpt-retrieval#3]
![image](https://github.com/techleadhd/chatgpt-retrieval/assets/96077395/e0bc313b-94ce-44ab-bbcb-eec41a0abf75)

**Comment by RickyWang111** [comment]
I solved this problem.  I use 0 instead 1

**Comment by RickyWang111** [comment]
```
PS F:\__4__code\gc_ziji\chatgpt-retrieval> python chatgpt.py "what is my dog's name"
Traceback (most recent call last):
  File "F:\__4__code\gc_ziji\chatgpt-retrieval\chatgpt.py", line 34, in <module>
    index = VectorstoreIndexCreator().from_loaders([loader])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\langchain\indexes\vectorstore.py", line 73, in from_loaders
    return self.from_documents(docs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\langchain\indexes\vectorstore.py", line 78, in from_documents
    vectorstore = self.vectorstore_cls.from_documents(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 435, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 403, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 149, in add_texts
    self._collection.add(
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\chromadb\api\models\Collection.py", line 96, in add
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\chromadb\api\models\Collection.py", line 347, in _validate_embedding_set
    ids = validate_ids(maybe_cast_one_to_many(ids))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 435, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 403, in from_texts
    chroma_collection.add_texts(texts=texts, metadatas=metadatas, ids=ids)
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\langchain\vectorstores\chroma.py", line 149, in add_texts
    self._collection.add(
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\chromadb\api\models\Collection.py", line 96, in add
    ids, embeddings, metadatas, documents = self._validate_embedding_set(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\chromadb\api\models\Collection.py", line 347, in _validate_embedding_set
    ids = validate_ids(maybe_cast_one_to_many(ids))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\__4__code\Program Files\Python\Python311\Lib\site-packages\chromadb\api\types.py", line 97, in maybe_cast_one_to_many
    if isinstance(target[0], (int, float)):
                  ~~~~~~^^^
IndexError: list index out of range
```
