### ISSUE TITLE
Problem with partition_pdf module

### ISSUE THREAD

**Issue by decsousa** [techleadhd/chatgpt-retrieval#32]
Hello, when I try to run the code the following error is displayed:

Traceback (most recent call last):
  File "C:\Users\Diego Sousa\Desktop\botchatgpt\botchatgpt\chat02.py", line 35, in <module>
    index = VectorstoreIndexCreator().from_loaders([loader])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Diego Sousa\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\indexes\vectorstore.py", line 72, in from_loaders
    docs.extend(loader.load())
                ^^^^^^^^^^^^^
  File "C:\Users\Diego Sousa\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\document_loaders\directory.py", line 137, in load
    self.load_file(i, p, docs, pbar)
  File "C:\Users\Diego Sousa\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\document_loaders\directory.py", line 94, in load_file
    raise e
  File "C:\Users\Diego Sousa\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\document_loaders\directory.py", line 88, in load_file
    sub_docs = self.loader_cls(str(item), **self.loader_kwargs).load()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Diego Sousa\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\document_loaders\unstructured.py", line 86, in load
    elements = self._get_elements()
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Diego Sousa\AppData\Local\Programs\Python\Python311\Lib\site-packages\langchain\document_loaders\unstructured.py", line 171, in _get_elements       
    return partition(filename=self.file_path, **self.unstructured_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Diego Sousa\AppData\Local\Programs\Python\Python311\Lib\site-packages\unstructured\partition\auto.py", line 221, in partition
    elements = partition_pdf(
               ^^^^^^^^^^^^^
NameError: name 'partition_pdf' is not defined. Did you mean: 'partition_xml'?

has anyone had this same problem?

**Comment by psujit775** [comment]
+1

**Comment by GavinXZhang** [comment]
+1

**Comment by JayKayNJIT** [comment]
Following

**Comment by fengmzhu** [comment]
+1

**Comment by 3dylson** [comment]
To make it work I had to:

at the file `.../site-packages/unstructured/partition/auto.py`

add the line: `from unstructured.partition.pdf import partition_pdf`

then `pip3 install pdf2image pdfminer.six`

last if you have macOS, search 'Install Certificates.command' in the finder and open it.

Then do the following steps in the terminal:

```
python3
import nltk
nltk.download()
```

**Comment by sephdm** [comment]
> To make it work I had to:
> 
> at the file `.../site-packages/unstructured/partition/auto.py`
> 
> add the line: `from unstructured.partition.pdf import partition_pdf`
> 
> then `pip3 install pdf2image pdfminer.six`
> 
> last if you have macOS, search 'Install Certificates.command' in the finder and open it.
> 
> Then do the following steps in the terminal:
> 
> ```
> python3
> import nltk
> nltk.download()
> ```

thanks man. You made it work for me. But FYI in my windows conda environment, after an hour of trying to make sense of where that folder was that you mentioned, i decided to simply see what happened if I used your pip three command to install PDFminer. And then the program worked. So I'm not sure what the first preamble was but it may not be necessary at all. Correct me if I'm wrong but maybe it's just windows you know

**Comment by bobbyfongprivate** [comment]
Downgrading to version 0.7.12 resolved the problem for me. You can do this by running the following command in your virtual environment:

pip install unstructured==0.7.12

**Comment by fire115** [comment]
pip install unstructured==0.7.12 works

**Comment by Zhi0467** [comment]
> To make it work I had to:
> 
> at the file `.../site-packages/unstructured/partition/auto.py`
> 
> add the line: `from unstructured.partition.pdf import partition_pdf`
> 
> then `pip3 install pdf2image pdfminer.six`
> 
> last if you have macOS, search 'Install Certificates.command' in the finder and open it.
> 
> Then do the following steps in the terminal:
> 
> ```
> python3
> import nltk
> nltk.download()
> ```

I tried this but then I got this error:
File "/Users/wangzhi/anaconda3/envs/chat/lib/python3.12/site-packages/langchain_community/document_loaders/unstructured.py", line 168, in _get_elements
    from unstructured.partition.auto import partition
  File "/Users/wangzhi/anaconda3/envs/chat/lib/python3.12/site-packages/unstructured/partition/auto.py", line 28, in <module>
    from unstructured.partition.pdf import partition_pdf
  File "/Users/wangzhi/anaconda3/envs/chat/lib/python3.12/site-packages/unstructured/partition/pdf.py", line 19, in <module>
    from pillow_heif import register_heif_opener
ModuleNotFoundError: No module named 'pillow_heif'

any ideas please? @3dylson
