### ISSUE TITLE
Will this no longer work?

### ISSUE THREAD

**Issue by soorajthekkepatt** [techleadhd/chatgpt-retrieval#63]
Traceback (most recent call last):
  File "/Users/sooraj/Documents/chat/chatgpt-retrieval/chatgpt.py", line 6, in <module>
    from langchain.chat_models import ChatOpenAI
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/chat_models/__init__.py", line 27, in __getattr__
    from langchain_community import chat_models
ModuleNotFoundError: No module named 'langchain_community'
iconv: iconv_open(, -t): Invalid argument
Error converting string from  to UTF-8

**Comment by Zhi0467** [comment]
This is the imports that worked for me:
`import os
import sys

import openai
from langchain.chains import ConversationalRetrievalChain, RetrievalQA
from langchain_openai import ChatOpenAI
from langchain_community.document_loaders import DirectoryLoader, TextLoader
from langchain_openai import OpenAIEmbeddings
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain_community.llms import OpenAI
from langchain_community.vectorstores import Chroma

import constants`

If you are using conda to install packages, I would suggest using _python -m pip install langchain-openai langchain-community langchain-core_ in your conda environment, and avoid using conda install, so that your conda can actually find these packages.

**Comment by TamimLikhon** [comment]
`import os
import sys

import openai
from langchain.chains import ConversationalRetrievalChain, RetrievalQA
from langchain_openai import ChatOpenAI
from langchain_community.document_loaders import DirectoryLoader, TextLoader
from langchain_openai import OpenAIEmbeddings
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper
from langchain_community.llms import OpenAI
from langchain_community.vectorstores import Chroma

import constants

os.environ["OPENAI_API_KEY"] = constants.APIKEY

PERSIST = False

query = None
if len(sys.argv) > 1:
  query = sys.argv[1]

if PERSIST and os.path.exists("persist"):
  print("Reusing index...\n")
  vectorstore = Chroma(persist_directory="persist", embedding_function=OpenAIEmbeddings())
  index = VectorStoreIndexWrapper(vectorstore=vectorstore)
else:
  #loader = TextLoader("data/data.txt") # Use this line if you only need data.txt
  loader = DirectoryLoader("data/")
  if PERSIST:
    index = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory":"persist"}).from_loaders([loader])
  else:
    index = VectorstoreIndexCreator().from_loaders([loader])

chain = ConversationalRetrievalChain.from_llm(
  llm=ChatOpenAI(model="gpt-3.5-turbo"),
  retriever=index.vectorstore.as_retriever(search_kwargs={"k": 1}),
)

chat_history = []
while True:
  if not query:
    query = input("Prompt: ")
  if query in ['quit', 'q', 'exit']:
    sys.exit()
  result = chain({"question": query, "chat_history": chat_history})
  print(result['answer'])

  chat_history.append((query, result['answer']))
  query = None`
  
  when I run - python chatgpt.py "What is my name" 
  output:
  ModuleNotFoundError: No module named 'langchain_community.indexes.vectorstore'

**Comment by Zhi0467** [comment]
have you installed langchain-core and langchain-community manually using pip install? Check if your Python interpreter can find these packages, e.g. go to site-packages 
or if you are using conda, stick to python -m pip install in the virtual env
of course, you can also try updating with pip install --upgrade langchain langchain-community

**Comment by TamimLikhon** [comment]
`import os
import sys

import openai
from langchain.chains import ConversationalRetrievalChain, RetrievalQA
from langchain.indexes import VectorstoreIndexCreator
from langchain.indexes.vectorstore import VectorStoreIndexWrapper

import constants
from langchain_community.document_loaders import DirectoryLoader, TextLoader
from langchain_community.vectorstores import Chroma
from langchain_openai import ChatOpenAI, OpenAI, OpenAIEmbeddings

os.environ["OPENAI_API_KEY"] = constants.APIKEY

# Enable to save to disk & reuse the model (for repeated queries on the same data)
PERSIST = False

query = None
if len(sys.argv) > 1:
  query = sys.argv[1]

if PERSIST and os.path.exists("persist"):
  print("Reusing index...\n")
  vectorstore = Chroma(persist_directory="persist", embedding_function=OpenAIEmbeddings())
  index = VectorStoreIndexWrapper(vectorstore=vectorstore)
else:
  #loader = TextLoader("data/data.txt") # Use this line if you only need data.txt
  loader = DirectoryLoader("data/")
  if PERSIST:
    index = VectorstoreIndexCreator(vectorstore_kwargs={"persist_directory":"persist"}).from_loaders([loader])
  else:
    index = VectorstoreIndexCreator().from_loaders([loader])

chain = ConversationalRetrievalChain.from_llm(
  llm=ChatOpenAI(model="gpt-3.5-turbo"),
  retriever=index.vectorstore.as_retriever(search_kwargs={"k": 1}),
)

chat_history = []
while True:
  if not query:
    query = input("Prompt: ")
  if query in ['quit', 'q', 'exit']:
    sys.exit()
  result = chain({"question": query, "chat_history": chat_history})
  print(result['answer'])

  chat_history.append((query, result['answer']))
  query = None
`

output: still same
Traceback (most recent call last):
  File "/home/tamim/Downloads/chatgpt-retrieval/chatgpt.py", line 6, in <module>
    from langchain.indexes import VectorstoreIndexCreator
  File "/home/tamim/.local/lib/python3.10/site-packages/langchain/indexes/__init__.py", line 20, in <module>
    from langchain.indexes.vectorstore import VectorstoreIndexCreator
  File "/home/tamim/.local/lib/python3.10/site-packages/langchain/indexes/vectorstore.py", line 8, in <module>
    from langchain_community.indexes.vectorstore import VectorstoreIndexCreator  # Adjusted import
ModuleNotFoundError: No module named 'langchain_community.indexes.vectorstore'

**Comment by LevYas** [comment]
It does not make sense to fix these errors one by one. I had to completely rewrite it, but it still is not as good as I wanted. Here I wrote about my experience, my script included https://yastr.dev/posts/genai-rag-pitfalls/

**Comment by KaySchneider** [comment]
@LevYas thank you for your updates on that.  Your Version looks really good and its actually workin  for me
