### ISSUE TITLE
The .gitignore references constants.py, but it is already checked in.

### ISSUE THREAD

**Issue by Wind010** [techleadhd/chatgpt-retrieval#9]
Nice work and informative video.

The constants.py file is already checked in and the `.gitignore` file will not ignore it.  Probably best to create a `secrets.py` for the `APIKEY` and update the readme.  

Create a `secrets.py` to use your own [OpenAI API key](https://platform.openai.com/account/api-keys):
```python
APIKEY = "YOUR_API_KEY"
```

Update the `.gitignore` with `secrets.py` instead of `constants.py`.  
Update `chatgpt.py` with 
```python
os.environ["OPENAI_API_KEY"] = secrets.API_KEY
```

Changes are not ignored by git if the file is already checked in.

**Comment by Wind010** [comment]
`secrets.py` is a bad choice...  `user_secrets.py` works.

```sh
Traceback (most recent call last):
  File "chatgpt.py", line 9, in <module>
    from langchain.chains import RetrievalQA
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\agents\__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\agents\agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\agents\tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\tools\__init__.py", line 54, in <module>
    from langchain.tools.powerbi.tool import (
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\tools\powerbi\tool.py", line 11, in <module>
    from langchain.chains.llm import LLMChain
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\chains\__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\chains\api\base.py", line 13, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\chains\api\prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\prompts\__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\prompts\chat.py", line 11, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\memory\__init__.py", line 33, in <module>
    from langchain.memory.vectorstore import VectorStoreRetrieverMemory
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\memory\vectorstore.py", line 10, in <module>
    from langchain.vectorstores.base import VectorStoreRetriever
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\vectorstores\__init__.py", line 2, in <module>
    from langchain.vectorstores.alibabacloud_opensearch import (
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\vectorstores\alibabacloud_opensearch.py", line 7, in <module>
    from langchain.embeddings.base import Embeddings
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\embeddings\__init__.py", line 15, in <module>
    from langchain.embeddings.fake import FakeEmbeddings
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\langchain\embeddings\fake.py", line 3, in <module>
    import numpy as np
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\numpy\__init__.py", line 152, in <module>
    from . import random
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\numpy\random\__init__.py", line 180, in <module>
    from . import _pickle
  File "C:\git\github\chatgpt-retrieval\.venv\lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 38, in init numpy.random.bit_generator
ImportError: cannot import name randbits
```

https://stackoverflow.com/questions/73055157/what-does-importerror-cannot-import-name-randbits-mean

**Comment by techleadhd** [comment]
Resolved
